controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

proposal_bundle_controllers:
    resource: '@ProposalBundle/config/routes.yaml'

ticket_bundle_controllers:
    resource: '@TicketBundle/config/routes.yaml'